name: Feature Request
description: Suggest a new feature or enhancement for Valero
title: "[Feature] "
labels: ["enhancement", "feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please fill out the form below.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: Currently, users have to...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: I think it should work like...
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: I also thought about...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my workflow
        - Critical - Blocking my work
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, mockups, or examples about the feature request
      placeholder: |
        - Screenshots
        - Mockups
        - Related issues
        - Examples from other platforms
    validations:
      required: false

  - type: textarea
    id: backend-implementation
    attributes:
      label: Backend Implementation
      description: Technical checklist for backend changes.
      value: |
        - [ ] Database Migrations
        - [ ] Models & Relationships
        - [ ] Controllers & Logic
        - [ ] API Endpoints / Routes
        - [ ] Tests
    validations:
      required: false

  - type: textarea
    id: frontend-implementation
    attributes:
      label: Frontend Implementation
      description: Technical checklist for frontend changes.
      value: |
        - [ ] Routes & Navigation
        - [ ] Views / Pages
        - [ ] UI Components
        - [ ] JavaScript / Interactivity
        - [ ] Styling (Tailwind)
    validations:
      required: false

  - type: textarea
    id: localization
    attributes:
      label: Localization
      description: Ensure all strings are translatable.
      value: |
        - [ ] English (en) keys
        - [ ] Romanian (ro) keys
    validations:
      required: false

  - type: textarea
    id: documentation
    attributes:
      label: Documentation
      description: Documentation updates required.
      value: |
        - [ ] Update README.md
        - [ ] Update Wiki
    validations:
      required: false

  - type: textarea
    id: verification
    attributes:
      label: Verification
      description: Steps to verify the feature works as expected.
      value: |
        - [ ] Automated Tests pass
        - [ ] Manual Verification
    validations:
      required: false
